Update imports to support IDA 7.2
`import idaapi` is needed to avoid:
```
C:\Program Files\IDA 7.2\plugins\ifl.py: name 'idaapi' is not defined
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.2\python\ida_idaapi.py", line 572, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files/IDA 7.2/plugins/ifl.py", line 1198, in <module>
    class IFLMenuHandler(idaapi.action_handler_t):
NameError: name 'idaapi' is not defined
```
`from idautils import *` is needed to avoid:
```
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.2/plugins/ifl.py", line 1007, in OnCreate
    self.funcMapper = FunctionsMapper_t()
  File "C:/Program Files/IDA 7.2/plugins/ifl.py", line 789, in __init__
    self._loadLocals()
  File "C:/Program Files/IDA 7.2/plugins/ifl.py", line 770, in _loadLocals
    for func in Functions():
NameError: global name 'Functions' is not defined
```